version: 2.1

orbs:
  python: circleci/python@0.2.1
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      - run:
          name: Install Dependencies
          command: |
            poetry install
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
      - run:
          name: Run Pytest
          command: |
            poetry run pytest
      - sonarcloud/scan
workflows:
  main:
    jobs:
      - build-and-test:
          context: SonarCloud
